#!/usr/bin/env bash

# Choose session directory
session=$(find ~ ~/projects -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

# Check if tmux is running
if ! tmux has-session -t "$session_name" 2>/dev/null; then
  # Start tmux if it's not already running
  tmux new-session -s "$session_name" -c "$session" -d "exec /bin/zsh --login"
fi

# Attach to tmux session
tmux switch-client -t "$session_name"
