- hosts: localhost
  become: true
  tasks:
    - name: Install zsh
      apt: name=zsh
    - name: Change shell
      shell: chsh -s `which zsh`
    - name: Install ohmyzsh
      shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    - name: Install ohmyzsh plugin for autocompletions
    - name: Install ohmyzsh plugin for ssh-agent
    - name: Install ohmyzsh plugin for vi-keys
    - name: Install cheat.sh 
      shell: curl -s https://cht.sh/:cht.sh | sudo tee /usr/local/bin/cht.sh && sudo chmod +x /usr/local/bin/cht.sh
